"""
Shared TLS helper for building SSL contexts from environment variables.

Used by the API server and all background workers for mutual TLS connections
to PostgreSQL, Redis, and MinIO.  All TLS behaviour is gated on the
TLS_ENABLED=true environment variable so that plain-HTTP local dev still works
without any certificates present.
"""

import os
import ssl


def build_ssl_context(
    *,
    ca_cert: str | None = None,
    client_cert: str | None = None,
    client_key: str | None = None,
) -> ssl.SSLContext | None:
    """
    Build an SSLContext suitable for mutual TLS connections.

    Returns None when TLS is disabled or when the CA cert file is absent,
    so callers can do ``connect_args={"ssl": build_ssl_context() or False}``.

    Args:
        ca_cert: Path to CA certificate PEM (defaults to TLS_CA_CERT env var)
        client_cert: Path to client certificate PEM (defaults to TLS_CLIENT_CERT)
        client_key: Path to client private key PEM (defaults to TLS_CLIENT_KEY)

    Returns:
        Configured SSLContext or None if TLS is not enabled / certs missing.
    """
    if os.getenv("TLS_ENABLED", "false").lower() != "true":
        return None

    ca = ca_cert or os.getenv("TLS_CA_CERT", "/tls/ca.crt")
    cert = client_cert or os.getenv("TLS_CLIENT_CERT", "/tls/client.crt")
    key = client_key or os.getenv("TLS_CLIENT_KEY", "/tls/client.key")

    if not os.path.exists(ca):
        return None

    ctx = ssl.create_default_context(cafile=ca)
    # Server certificates include DNS SANs for each Docker service name
    # (postgres, redis, minio) — generated by docker/tls/generate_certs.sh.
    # Hostname verification is enabled to prevent MITM on the internal network.
    ctx.check_hostname = True

    if os.path.exists(cert) and os.path.exists(key):
        ctx.load_cert_chain(cert, key)

    return ctx


def redis_tls_kwargs() -> dict:
    """
    Return keyword arguments for redis.from_url() that enable mutual TLS.

    Returns an empty dict when TLS is disabled so callers can always do:
        redis.from_url(url, **redis_tls_kwargs())

    Returns:
        Dict with ssl_certfile, ssl_keyfile, ssl_ca_certs, ssl_check_hostname
        keys when TLS is active; empty dict otherwise.
    """
    if os.getenv("TLS_ENABLED", "false").lower() != "true":
        return {}

    return {
        "ssl_certfile": os.getenv("TLS_CLIENT_CERT", "/tls/client.crt"),
        "ssl_keyfile": os.getenv("TLS_CLIENT_KEY", "/tls/client.key"),
        "ssl_ca_certs": os.getenv("TLS_CA_CERT", "/tls/ca.crt"),
        "ssl_check_hostname": True,
    }
